### ISSUE TITLE
Problem mounting /etc/vomses in opensciencegrid/osg-wn images

### ISSUE THREAD

**Issue by smuzaffar** [opensciencegrid/docker-osg-wn#4]
I am having trobles mounting to /etc/vomses   for opensciencegrid/osg-wn images. I think problem is that `/etc/vomses` is a file (instead of a directory) in the container . So what is the correct why to mount this? 

```
singularity run -B /cvmfs/grid.cern.ch/etc/grid-security/vomses:/etc/vomses  docker://opensciencegrid/osg-wn:3.4-el7 bash
FATAL:   container creation failed: mount /cvmfs/grid.cern.ch/etc/grid-security/vomses->/etc/vomses error: while mounting /cvmfs/grid.cern.ch/etc/grid-security/vomses: could not mount /cvmfs/grid.cern.ch/etc/grid-security/vomses: not a directory
```

**Comment by efajardo** [comment]
@smuzaffar `/etc/vomses/` is a file in OSG. What are you trying to achieve. Which CERN voms do you need that it is not in the OSG vomses?

**Comment by smuzaffar** [comment]
for some unknown reason, I felt thatfile was empty :-) sorry for the noise, all is good.
