### ISSUE TITLE
opensciencegrid/osg-wn:3.4-el6: yum repo mirror and xz issue

### ISSUE THREAD

**Issue by smuzaffar** [opensciencegrid/docker-osg-wn#5]
We use `opensciencegrid/osg-wn:3.4-el6` to build `cmssw/cms:rhel6` docker containers. There are coupe of issues we see when using `docker run --rm --net=host -it opensciencegrid/osg-wn:3.4-el6 `
- Running yum gives repo mirror errors
```
[root@cmsdocker06 /]# yum install gcc
Loaded plugins: fastestmirror, ovl, priorities
Setting up Install Process
Determining fastest mirrors
YumRepo Error: All mirror URLs are not using ftp, http[s] or file.
 Eg. Invalid release/repo/arch combination/
removing mirrorlist with no valid mirrors: /var/cache/yum/x86_64/6/base/mirrorlist.txt
Error: Cannot find a valid baseurl for repo: base
```
This we have fixed by adding the following in our dockerfile ( https://github.com/cms-sw/cms-docker/blob/master/cms/Dockerfile.rhel6 )
```
RUN sed -i -e 's|^mirrorlist=|#mirrorlist=|;s|^#baseurl=|baseurl=|' /etc/yum.repos.d/CentOS-Base.repo && \
    sed -i -e 's|/mirror.centos.org/|/vault.centos.org/|' /etc/yum.repos.d/CentOS-Base.repo
```

- Now we are getting error "Error: xz compression not available"
```
[root@cmsdocker06 /]# yum install gcc
Loaded plugins: fastestmirror, ovl, priorities
Setting up Install Process
Loading mirror speeds from cached hostfile
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * osg: mirror.grid.uchicago.edu
Error: xz compression not available
```

`xz` is only needed for centos7. Looks like osg repos ( `/etc/yum.repos.d/osg-el6*.repo` ) are casuing this. If I move away the `osg-el6*.repo`  e.g. `for r in /etc/yum.repos.d/osg-*.repo ; do mv $r $r.old ; done` then I am able to build `cmssw/cms:rhel6` container.

Any idea what could be wrong with `osg-el6*.repo` repository definitions?

**Comment by brianhlin** [comment]
Hi @smuzaffar , we no longer support OSG 3.4 (https://opensciencegrid.org/technology/policy/release-series/) and EL6 is also out of support. Have you considered updating to OSG 3.5 (or 3.6) and EL7?

**Comment by smuzaffar** [comment]
For EL7, we are already using OSG 3.5. I will check with CMS computing team if it is OK to move to OSG 3.6 for EL7.
There was a request to re-build cmssw/cms:rhel6  container and the build process  failed due to the error mentioned above.

**Comment by brianhlin** [comment]
Thanks @smuzaffar. It's worth noting that OSG 3.6 is dropping Globus from its software stack (https://opensciencegrid.org/technology/policy/gridftp-gsi-migration/) so there may be some issues there.
